{
    "openapi": "3.0.0",
    "info": {
      "title": "Quip Admin API",
      "version": "1",
      "description": "## Summary\nFor governance and security purposes, Quip makes available a set of APIs to\nenable specific users to see all content within a Quip site and to take\nactions against that content.\n\n## Requirements\nThis API requires that you have first followed the setup instructions for\nthe <a href=\"/dev/automation/documentation\" target=\"_blank\">Quip Automation API</a>.\n\nTo call this API, the access token you use must be for a user who is an\nadmin.\n\nYou must also ha[...]"
    },
    "servers": [
      {
        "url": "https://platform.quip.com/1"
      }
    ],
    "tags": [
      {
        "name": "Threads"
      },
      {
        "name": "Messages"
      },
      {
        "name": "Users"
      },
      {
        "name": "Folders"
      },
      {
        "name": "Events (requires subscription)",
        "description": "<pre style=\"color:#353535\">\n| Event Type           | Description                                                       |\n| -------------------- | ----------------------------------------------------------------- |\n| create-thread        | A thread was created. Additional data on the type of creation can |\n|                      | be found in sub_action; the options are: create-new,              |\n|                      | create-import, create-copy                  [...]"
      },
      {
        "name": "Quarantine"
      },
      {
        "name": "Company"
      },
      {
        "name": "Admin Roles"
      },
      {
        "name": "Governance (requires subscription)"
      }
    ],
    "components": {
      "securitySchemes": {
        "OAuth2": {
          "flows": {
            "authorizationCode": {
              "authorizationUrl": "https://platform.quip.com/1/oauth/login",
              "refreshUrl": "https://platform.quip.com/1/oauth/access_token",
              "scopes": {
                "ADMIN_MANAGE": "",
                "ADMIN_READ": "",
                "ADMIN_WRITE": ""
              },
              "tokenUrl": "https://platform.quip.com/1/oauth/access_token"
            }
          },
          "type": "oauth2"
        }
      }
    },
    "paths": {
      "/admin/blob/{thread_id}/{blob_id}": {
        "get": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_READ"
              ]
            }
          ],
          "tags": [
            "Threads"
          ],
          "summary": "Get a Blob from a Thread",
          "operationId": "getBlob",
          "description": "Returns the contents of specified blob from the thread.\n"
        }
      },
      "/admin/blob/{thread_id}": {
        "post": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_WRITE"
              ]
            }
          ],
          "tags": [
            "Threads"
          ],
          "summary": "Add a Blob to a Thread",
          "operationId": "addBlobToThread",
          "description": "Uploads an image or other blob to the given thread. Returns a `url`\nthat may be used in the `content` field of\n[Edit Document](#operation/editDocument)\nrequests and an `id` that may be used in the `attachment` field of\n[Add a Message](#operation/addMessage).\n\n\n### Response Fields\n\n**`id`**\n\n\nThe new blob ID.\n\n\n**`url`**\n\n\nThe relative URL to reference the blob in document edits.\n"
        }
      },
      "/admin/company/collaborating-companies/{external_company_id}": {
        "get": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_READ"
              ]
            }
          ],
          "tags": [
            "Company"
          ],
          "summary": "Get Collaborating Company",
          "operationId": "getCollaboratingCompany",
          "description": "Returns information about a company you are collaborating with,\nincluding the threads you are collaborating on\n"
        }
      },
      "/admin/company/collaborating-companies/list": {
        "post": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_READ"
              ]
            }
          ],
          "tags": [
            "Company"
          ],
          "summary": "Get Collaborating Companies",
          "operationId": "getCollaboratingCompanies",
          "description": "Returns all companies you are collaborating with\n"
        }
      },
      "/admin/company/managed-sites": {
        "get": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_MANAGE"
              ]
            }
          ],
          "tags": [
            "Company"
          ],
          "summary": "Get Managed Sites",
          "operationId": "getManagedSites",
          "description": "Returns a list of all managed site IDs for the admin's company.\n"
        },
        "post": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_MANAGE"
              ]
            }
          ],
          "tags": [
            "Company"
          ],
          "summary": "Create Managed Sites",
          "operationId": "createManagedSites",
          "description": "Creates a batch of new managed sites for the admin's company.\n\n### Request Body\n\nThe request body consists of one site object, or an array of site\nobjects. A site object is defined below.\n\n\n`company_id`\n\nThe company to use\n\n`site_type`\n\n\"partner\" or \"testing\"\n\n`name`\n\nThe name of the new managed site\n\n`subdomain`\n\nThe subdomain for the new managed site\n\n`only_able_to_share_with_main_site` OPTIONAL\n\ntrue/false, Restrict external sharing to o[...]"
        },
        "delete": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_MANAGE"
              ]
            }
          ],
          "tags": [
            "Company"
          ],
          "summary": "Delete Managed Sites",
          "operationId": "deleteManagedSites",
          "description": "Disables a batch of managed sites.\n"
        }
      },
      "/admin/data-hold-policy": {
        "get": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_MANAGE"
              ]
            }
          ],
          "tags": [
            "Governance (requires subscription)"
          ],
          "summary": "Get Data Hold",
          "operationId": "getDataHold",
          "description": "Returns the data hold policy.\n"
        },
        "post": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_WRITE"
              ]
            }
          ],
          "tags": [
            "Governance (requires subscription)"
          ],
          "summary": "Create Data Hold",
          "operationId": "createDataHold",
          "description": "Creates a data hold policy.\n\n### Request Body\n\n`company_id`\nThe company to use\n\n`name`\nThe name of the data hold policy.\n\n`start_date`\nThe start date of the data hold in the format \"yyyy-mm-dd\"\n\n`end_date`\nThe end date of the data hold in the format \"yyyy-mm-dd\"\n\n`member_emails`\nAn array of emails to add to the data hold.\n"
        },
        "delete": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_WRITE"
              ]
            }
          ],
          "tags": [
            "Governance (requires subscription)"
          ],
          "summary": "Retire Data Hold",
          "operationId": "retireDataHold",
          "description": "Retires a data hold policy.\n\n### Request Body\n\n`company_id`\nThe company to use\n\n`policy_id`\nThe id of the data hold policy to retire.\n"
        }
      },
      "/admin/data-hold-policy/users": {
        "post": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_WRITE"
              ]
            }
          ],
          "tags": [
            "Governance (requires subscription)"
          ],
          "summary": "Add Users to Data Hold",
          "operationId": "addUsersToDataHold",
          "description": "Adds users to a data hold policy.\n\n### Request Body\n\n`company_id`\nThe company to use\n\n`policy_id`\nThe id of the data hold policy to add users to.\n\n`member_emails`\nAn array of emails to add to the data hold.\n"
        },
        "delete": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_WRITE"
              ]
            }
          ],
          "tags": [
            "Governance (requires subscription)"
          ],
          "summary": "Remove Users from Data Hold",
          "operationId": "removeUsersFromDataHold",
          "description": "Removes users from a data hold policy.\n\n### Request Body\n\n`company_id`\nThe company to use\n\n`policy_id`\nThe id of the data hold policy to remove users from.\n\n`member_emails`\nAn array of emails to remove from the data hold.\n"
        }
      },
      "/admin/events/1/cursor/create": {
        "get": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_READ"
              ]
            }
          ],
          "tags": [
            "Events (requires subscription)"
          ],
          "summary": "Get an Event Cursor",
          "operationId": "getEventCursor",
          "description": "Gets a starting cursor to retrieve historical events.\n"
        }
      },
      "/admin/events/1/cursor/realtime/create": {
        "get": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_READ"
              ]
            }
          ],
          "tags": [
            "Events (requires subscription)"
          ],
          "summary": "Get a Cursor for Near Real-Time Events",
          "operationId": "getRealtimeEventCursor",
          "description": "Gets a starting cursor to retrieve historical events.\n\nNote that near real-time cursors expire 24 hours after creation,\nincluding `next_cursor`s provided when getting a batch of events.\n"
        }
      },
      "/admin/events/1/events/get": {
        "get": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_READ"
              ]
            }
          ],
          "tags": [
            "Events (requires subscription)"
          ],
          "summary": "Get Next Batch of Events",
          "operationId": "getEvents",
          "description": "Returns the next batch of historical events from the cursor argument.\n\nResponse contains list of zero or more events, whose format and\ncontent fields are described above.\n"
        }
      },
      "/admin/events/1/events/realtime/get": {
        "get": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_READ"
              ]
            }
          ],
          "tags": [
            "Events (requires subscription)"
          ],
          "summary": "Get Next Batch of Near Real-Time Events",
          "operationId": "getRealtimeEvents",
          "description": "Returns the next batch of historical events from the cursor argument.\n\nResponse contains list of zero or more events, whose format and\ncontent fields are described above.\n"
        }
      },
      "/admin/folders/{id}": {
        "get": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_READ"
              ]
            }
          ],
          "tags": [
            "Folders"
          ],
          "summary": "Get a Folder",
          "operationId": "getFolder",
          "description": "Get information about any folder.\n"
        }
      },
      "/admin/message/delete": {
        "post": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_WRITE"
              ]
            }
          ],
          "tags": [
            "Messages"
          ],
          "summary": "Delete a Message",
          "operationId": "deleteMessage",
          "description": "Delete a message with the given message ID.\n"
        }
      },
      "/admin/message/{message_id}": {
        "get": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_READ"
              ]
            }
          ],
          "tags": [
            "Messages"
          ],
          "summary": "Get a Message",
          "operationId": "getMessage",
          "description": "Returns a message with the given message ID.\n"
        }
      },
      "/admin/messages/{thread_id}": {
        "get": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_READ"
              ]
            }
          ],
          "tags": [
            "Messages"
          ],
          "summary": "Get Messages for a Thread",
          "operationId": "getMessagesForThread",
          "description": "Returns a list of the most recent messages for the given thread,\nordered reverse-chronologically.\n"
        }
      },
      "/admin/quarantine": {
        "post": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_MANAGE"
              ]
            }
          ],
          "tags": [
            "Quarantine"
          ],
          "summary": "Add Quarantine",
          "operationId": "addQurantine",
          "description": "Quarantines a given object, either a message or a document or a blob.\nQuarantining a document hides all document content, including the\ntitle, and blocks all edits.\n\nQuarantining a message hides all message content.\n\nQuarantining a blob prevents accessing the blob.\n"
        },
        "delete": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_MANAGE"
              ]
            }
          ],
          "tags": [
            "Quarantine"
          ],
          "summary": "Remove Quarantine",
          "operationId": "removeQurantine",
          "description": "Remove a document or message from quarantine. This will restore its\ncontent to its pre-quarantine state.\n"
        }
      },
      "/admin/threads/add-members": {
        "post": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_MANAGE"
              ]
            }
          ],
          "tags": [
            "Threads"
          ],
          "summary": "Add People to a Thread or Add a Thread to Folders",
          "operationId": "addThreadMembers",
          "description": "The member_ids parameter must contain a list of folder IDs and user\nIDS. Specified users will be added to the document and the thread\nwill be added to the specified folders.\n"
        }
      },
      "/admin/threads/copy-document": {
        "post": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_READ",
                "ADMIN_WRITE"
              ]
            }
          ],
          "tags": [
            "Threads"
          ],
          "summary": "Copy a Document or Template",
          "operationId": "copyDocumentOrTemplate",
          "description": "Makes a copy of the document specified by the `thread_id` argument.\nThe source document can also be treated as a template. To use the\nsource document as a template, the `values` query argument must\ncontain a valid JSON dictionary that consists of string keys and\nwhose values are either string, numbers or other dictionaries. The\nendpoint will scan the document for a text pattern like:\n\n\n```\n\n[[varname]]\n\n```\n\n\nwhere varname consists of a series of alphanum[...]"
        }
      },
      "/admin/threads/delete": {
        "post": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_MANAGE"
              ]
            }
          ],
          "tags": [
            "Threads"
          ],
          "summary": "Delete a Thread",
          "operationId": "deleteThreads",
          "description": "Deletes the thread with the specified id or secret.\n\n\n### RESPONSE FIELDS\n\n\nNo JSON is returned by this endpoint when successful. On an error,\nthere are three fields returned:\n\n\n`error`\n\n\nThe type of error\n\n\n`error_code`\n\n\nThe status code of the http request\n\n\n`error_description`\n\n\nA short description of why the request failed\n"
        }
      },
      "/admin/threads/edit-document": {
        "post": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_WRITE"
              ]
            }
          ],
          "tags": [
            "Threads"
          ],
          "summary": "Edit A Document",
          "operationId": "editDocument",
          "description": "Incrementally modifies the content of a document.\n\n\nWe determine where to insert the new content based on the `location`\nargument. Some `location` values are relative to another section,\nwhich is specified by `section_id`, enabling fine-grained editing. For\nexample, to add an item to the end of a checklist, you would send the\nID of the last list item in the list as the `section_id` and send `2:\nAFTER_SECTION` as the `location`.\n\n\nTo get the IDs of sections in[...]"
        }
      },
      "/admin/threads/edit-share-link-settings": {
        "post": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_MANAGE"
              ]
            }
          ],
          "tags": [
            "Threads"
          ],
          "summary": "Edit Thread Share Link Settings",
          "operationId": "editShareLinkSettings",
          "description": "Allows the api user to change the link-shared settings of any thread\n"
        }
      },
      "/admin/threads/{thread_id}/export/docx": {
        "get": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_READ"
              ]
            }
          ],
          "tags": [
            "Threads"
          ],
          "summary": "Export Document to .docx",
          "operationId": "exportThreadToDocx"
        }
      },
      "/admin/threads/{thread_id}/export/pdf": {
        "get": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_READ"
              ]
            }
          ],
          "tags": [
            "Threads"
          ],
          "summary": "Export Slides to .pdf",
          "operationId": "exportThreadToPdf"
        }
      },
      "/admin/threads/{thread_id}/export/xlsx": {
        "get": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_READ"
              ]
            }
          ],
          "tags": [
            "Threads"
          ],
          "summary": "Export Spreadsheet to .xlsx",
          "operationId": "exportThreadToXlsx"
        }
      },
      "/admin/threads/external/list": {
        "post": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_READ"
              ]
            }
          ],
          "tags": [
            "Threads"
          ],
          "summary": "Get Externally Shared Threads",
          "operationId": "listExternalThreads",
          "description": "Retrieve details on a list of threads\n"
        }
      },
      "/admin/threads/{id}": {
        "get": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_READ"
              ]
            }
          ],
          "tags": [
            "Threads"
          ],
          "summary": "Get a Thread",
          "operationId": "getThread",
          "description": "Retrieve information about a specific thread.\n"
        }
      },
      "/admin/threads/list": {
        "post": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_READ"
              ]
            }
          ],
          "tags": [
            "Threads"
          ],
          "summary": "List Threads",
          "operationId": "listThreads",
          "description": "Returns a list of all threads in the company along with a timestamp\nwhen they were last modified.\n"
        }
      },
      "/admin/threads": {
        "get": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_READ"
              ]
            }
          ],
          "tags": [
            "Threads"
          ],
          "summary": "Get Threads by ID",
          "operationId": "getThreadsById",
          "description": "Retrieve details on a list of threads\n"
        }
      },
      "/admin/threads/new-document": {
        "post": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_WRITE"
              ]
            }
          ],
          "tags": [
            "Threads"
          ],
          "summary": "Create a Document, Spreadsheet or Slides",
          "operationId": "newDocument",
          "description": "Creates a document, spreadsheet, or slides, returning the new thread\nin the same format as [Get Thread](#operation/getThread).\n\nNote that for slides threads, this endpoint currently only supports\ncreating a bare-bones, one-slide deck with a given title. [Copy a\nDocument or Template](#operation/copyDocumentOrTemplate) provides\nfuller slides functionality, allowing automatic creation of a new\nslide deck adapted from an existing one.\n"
        }
      },
      "/threads/remove-external-members": {
        "post": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_MANAGE"
              ]
            }
          ],
          "tags": [
            "Threads"
          ],
          "summary": "Remove All External Users from a Thread",
          "operationId": "removeExternalThreadMembers",
          "description": "All external users will be removed from the thread.\n"
        }
      },
      "/admin/threads/remove-members": {
        "post": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_MANAGE"
              ]
            }
          ],
          "tags": [
            "Threads"
          ],
          "summary": "Remove People from a Thread or Remove a Thread from Folders",
          "operationId": "removeThreadMembers",
          "description": "The member_ids parameter must contain a list of folder IDs and user\nIDS. Specified users will be removed from the thread and the thread\nwill be removed from specified folders.\n"
        }
      },
      "/admin/threads/search": {
        "get": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_READ"
              ]
            }
          ],
          "tags": [
            "Threads"
          ],
          "summary": "Search for Threads",
          "operationId": "searchForThreads",
          "description": "Returns all documents that contain words specified in the \"query\"\nparameter.\n\n\nAdditional rate limits, separate from overall Admin API\n[Rate Limit](#section/Rate-Limit), are imposed for paginating over\nadmin search results.\n"
        }
      },
      "/admin/threads/set-live-reports-owner": {},
      "/admin/users/admin-role": {
        "get": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_READ"
              ]
            }
          ],
          "tags": [
            "Admin Roles"
          ],
          "summary": "Get Admin Role for a User",
          "operationId": "getAdminRoleForUser",
          "description": "Returns the admin role id and admin role name given a user id.\n"
        },
        "post": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_WRITE"
              ]
            }
          ],
          "tags": [
            "Admin Roles"
          ],
          "summary": "Set Admin Role for a User",
          "operationId": "setAdminRoleForUser",
          "description": "Updates a given user's admin role."
        },
        "delete": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_WRITE"
              ]
            }
          ],
          "tags": [
            "Admin Roles"
          ],
          "summary": "Delete Admin Role for a User",
          "operationId": "deleteAdminRoleForUser",
          "description": "Removes a given user's admin role and removes them as an admin.\n"
        }
      },
      "/admin/company/admin-roles": {
        "get": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_READ"
              ]
            }
          ],
          "tags": [
            "Admin Roles"
          ],
          "summary": "Get Admin Roles for a Company",
          "operationId": "getAdminRolesForCompany",
          "description": "Returns a list of all the admin role ids and admin role names.\n"
        }
      },
      "/admin/users/{id}": {
        "get": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_READ"
              ]
            }
          ],
          "tags": [
            "Users"
          ],
          "summary": "Get Information about a User",
          "operationId": "getUserInfo",
          "description": "Returns information about the specified user. When no optional\nparameters are present, the return value is a dictionary that contains\nthree lists, one for each of the user's threads, contacts and\ncompanies.\n\n\nFor larger companies, this information can become too large to\nreturn in one request. There are four optional parameters that\nclients can use to page through this information.\n\n### Optional Parameters\n\n* `since_updated_usec` - limits the number of entri[...]"
        }
      },
      "/admin/users/list": {
        "post": {
          "security": [
            {
              "OAuth2": [
                "ADMIN_READ"
              ]
            }
          ],
          "tags": [
            "Users"
          ],
          "summary": "List Users at a Company",
          "operationId": "listUsersAtCompany",
          "description": "Returns a list of users in the company.The list contains the name,\nemails, and id of each user.\n"
        }
      }
    }
  }